### ISSUE TITLE
Bug: 发送联系人信息错误

### ISSUE THREAD

**Issue by xueweiwujxw** [chenbb0128/moyu-chat#1]
##  复现过程
* 发送指令 `curl http://127.0.0.1:3000/sendContactMsg\?name\=Jixiangwuwxw'&'content\=测试消息`
* 指令返回 `联系人消息成功`，但是服务报错`ERR 发送联系人信息错误`
* 修改`sendMessage.ts`
```diff
diff --git a/src/services/sendMessage.ts b/src/services/sendMessage.ts
index 95b3cc3..4e733fe 100644
--- a/src/services/sendMessage.ts
+++ b/src/services/sendMessage.ts
@@ -15,7 +15,7 @@ export async function sendContactMsg(bot: Wechaty, content: string, alias?: stri
       contact.say(content)
   }
   catch (error) {
-    log.error('发送联系人信息错误')
+    log.error('发送联系人信息错误', error)
   }
 }
```
* 报错`ERR 发送联系人信息错误 Error: query must provide at least one key. current query is empty.`

**Comment by raintoway** [comment]
中文乱码，这个pr修复了https://github.com/chenbb0128/moyu-chat/pull/2

**Comment by chenbb0128** [comment]
> 中文乱码，这个pr修复了#2

已经合并，感谢修复
