### ISSUE TITLE
显示发送消息成功，但是微信上没有显示

### ISSUE THREAD

**Issue by Evanzew** [chenbb0128/moyu-chat#3]
![image](https://github.com/chenbb0128/moyu-chat/assets/27945478/e62bd68b-18ad-4ddb-aff8-109deb8f84ce)

**Comment by chenbb0128** [comment]
联系人的接口：http://127.0.0.1:3000/sendContactMsg?alias=xxx&content=xxx

**Comment by chenbb0128** [comment]
> ![image](https://private-user-images.githubusercontent.com/27945478/286846151-e62bd68b-18ad-4ddb-aff8-109deb8f84ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjg5NzQsIm5iZiI6MTcwMTMyODY3NCwicGF0aCI6Ii8yNzk0NTQ3OC8yODY4NDYxNTEtZTYyYmQ2OGItMThhZC00ZGRiLWFmZjgtMTA5ZGViOGY4NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjQ5NGY4NGQ0MTM0YzFjZWE0NjJmNzAzN2E4NjNlZTI1MjFjYTg0YTI4MzFkOThkYWFkYWVjOTc1MDhkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQbxQB4e3fZmb9BTyLATs7hmhrspNpb_UC_RbNjILyA)

联系人的接口：http://127.0.0.1:3000/sendContactMsg?alias=xxx&content=xxx

**Comment by Evanzew** [comment]
我看代码里判断是的/0或者/1，我使用你的sendcontactmsg报错cannot find，现在是接收没问题但是发送有问题，我使用的是windows，node版本是16，pnpm版本是7xx，是不是因为node版本不够？



> > ![image](https://private-user-images.githubusercontent.com/27945478/286846151-e62bd68b-18ad-4ddb-aff8-109deb8f84ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjg5NzQsIm5iZiI6MTcwMTMyODY3NCwicGF0aCI6Ii8yNzk0NTQ3OC8yODY4NDYxNTEtZTYyYmQ2OGItMThhZC00ZGRiLWFmZjgtMTA5ZGViOGY4NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjQ5NGY4NGQ0MTM0YzFjZWE0NjJmNzAzN2E4NjNlZTI1MjFjYTg0YTI4MzFkOThkYWFkYWVjOTc1MDhkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQbxQB4e3fZmb9BTyLATs7hmhrspNpb_UC_RbNjILyA)
> 
> 联系人的接口：http://127.0.0.1:3000/sendContactMsg?alias=xxx&content=xxx

我看代码里判断是的/0或者/1，我使用你的sendcontactmsg报错cannot find，现在是接收没问题但是发送有问题，我使用的是windows，node版本是16，pnpm版本是7xx，是不是因为node版本不够？

![image](https://github.com/chenbb0128/moyu-chat/assets/27945478/51ecb385-2afd-4777-b505-351b6577d54f)

**Comment by chenbb0128** [comment]
> 我看代码里判断是的/0或者/1，我使用你的sendcontactmsg报错cannot find，现在是接收没问题但是发送有问题，我使用的是windows，node版本是16，pnpm版本是7xx，是不是因为node版本不够？
> 
> > > ![image](https://private-user-images.githubusercontent.com/27945478/286846151-e62bd68b-18ad-4ddb-aff8-109deb8f84ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjg5NzQsIm5iZiI6MTcwMTMyODY3NCwicGF0aCI6Ii8yNzk0NTQ3OC8yODY4NDYxNTEtZTYyYmQ2OGItMThhZC00ZGRiLWFmZjgtMTA5ZGViOGY4NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjQ5NGY4NGQ0MTM0YzFjZWE0NjJmNzAzN2E4NjNlZTI1MjFjYTg0YTI4MzFkOThkYWFkYWVjOTc1MDhkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQbxQB4e3fZmb9BTyLATs7hmhrspNpb_UC_RbNjILyA)
> > 
> > 
> > 联系人的接口：http://127.0.0.1:3000/sendContactMsg?alias=xxx&content=xxx
> 
> 我看代码里判断是的/0或者/1，我使用你的sendcontactmsg报错cannot find，现在是接收没问题但是发送有问题，我使用的是windows，node版本是16，pnpm版本是7xx，是不是因为node版本不够？
> 
> ![image](https://private-user-images.githubusercontent.com/27945478/286853903-51ecb385-2afd-4777-b505-351b6577d54f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEwNTIsIm5iZiI6MTcwMTMzMDc1MiwicGF0aCI6Ii8yNzk0NTQ3OC8yODY4NTM5MDMtNTFlY2IzODUtMmFmZC00Nzc3LWI1MDUtMzUxYjY1NzdkNTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NWNmYjBmYTdiYTFlMmNlY2VkN2I1M2ZhZmU0MTY3M2M4Njg3Y2Q0NjY1NTg2NjE2MjIwNjQ4MDlkMjgxYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MyHZHIpgroYBYez2M5J2TliE8axbmWezKSnmxJUIQeM)

和版本没关系，这个接口搜索只能去搜索有备注的联系人，所以没有找到，你试试用一个有备注的人，用alias=xxx

**Comment by Evanzew** [comment]
> > 我看代码里判断是的/0或者/1，我使用你的sendcontactmsg报错cannot find，现在是接收没问题但是发送有问题，我使用的是windows，node版本是16，pnpm版本是7xx，是不是因为node版本不够？
> > > > ![image](https://private-user-images.githubusercontent.com/27945478/286846151-e62bd68b-18ad-4ddb-aff8-109deb8f84ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjg5NzQsIm5iZiI6MTcwMTMyODY3NCwicGF0aCI6Ii8yNzk0NTQ3OC8yODY4NDYxNTEtZTYyYmQ2OGItMThhZC00ZGRiLWFmZjgtMTA5ZGViOGY4NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjQ5NGY4NGQ0MTM0YzFjZWE0NjJmNzAzN2E4NjNlZTI1MjFjYTg0YTI4MzFkOThkYWFkYWVjOTc1MDhkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQbxQB4e3fZmb9BTyLATs7hmhrspNpb_UC_RbNjILyA)
> > > 
> > > 
> > > 联系人的接口：http://127.0.0.1:3000/sendContactMsg?alias=xxx&content=xxx
> > 
> > 
> > 我看代码里判断是的/0或者/1，我使用你的sendcontactmsg报错cannot find，现在是接收没问题但是发送有问题，我使用的是windows，node版本是16，pnpm版本是7xx，是不是因为node版本不够？
> > ![image](https://private-user-images.githubusercontent.com/27945478/286853903-51ecb385-2afd-4777-b505-351b6577d54f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEwNTIsIm5iZiI6MTcwMTMzMDc1MiwicGF0aCI6Ii8yNzk0NTQ3OC8yODY4NTM5MDMtNTFlY2IzODUtMmFmZC00Nzc3LWI1MDUtMzUxYjY1NzdkNTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NWNmYjBmYTdiYTFlMmNlY2VkN2I1M2ZhZmU0MTY3M2M4Njg3Y2Q0NjY1NTg2NjE2MjIwNjQ4MDlkMjgxYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MyHZHIpgroYBYez2M5J2TliE8axbmWezKSnmxJUIQeM)
> 
> 和版本没关系，这个接口搜索只能去搜索有备注的联系人，所以没有找到，你试试用一个有备注的人，用alias=xxx

还是报一样的错误
我使用readme里的接口，显示发送消息成功但是微信上接收不到
![Uploading image.png…]()

**Comment by Evanzew** [comment]
看了下原因，代码里 
```
const contact = await bot.Contact.find(query)
    if (contact) {
      contact.say(content)
```
这里没有找到contact

**Comment by Evanzew** [comment]
现在alias或者name使用英文是可以发送成功的，只是发送成功后content还是乱码

**Comment by Evanzew** [comment]
我自己解决了，我发现代码里的string2utf8不生效，我用了其他的方式改好了发成功了，thx
